openapi: 3.2.0
info:
  title: Beacon Rest Services Reject Saved Order API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: RejectSavedOrder
paths:
  /rejectSavedOrder:
    post:
      operationId: V2Controller_rejectSavedOrder
      summary: Allows approver to reject pending order
      description: Allows approver to reject pending order.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rejectSavedOrderBody'
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - RejectSavedOrder
components:
  schemas:
    rejectSavedOrderBody:
      type: object
      properties:
        rejectReason:
          type: string
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
      required:
      - rejectReason
      - orders
    Order:
      type: object
      properties:
        total:
          type: number
        sellingBranch:
          type: string
        accountId:
          type: string
        orderNumber:
          type: string
        job:
          $ref: '#/components/schemas/Job'
        purchaseOrderNo:
          type: string
        creditHold:
          type: string
        shipping:
          $ref: '#/components/schemas/Shipping'
        orderPlacedDate:
          type: string
        tax:
          type: number
        orderStatusCode:
          type: string
        subTotal:
          type: number
        orderId:
          type: string
        specialInstruction:
          type: string
        UUID:
          type: string
      required:
      - total
      - sellingBranch
      - accountId
      - orderNumber
      - job
      - purchaseOrderNo
      - creditHold
      - shipping
      - orderPlacedDate
      - tax
      - orderStatusCode
      - subTotal
      - orderId
      - specialInstruction
      - UUID
    Address:
      type: object
      properties:
        postalCode:
          type: string
        state:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        country:
          type: string
        city:
          type: string
      required:
      - postalCode
      - state
      - address1
      - address2
      - address3
      - country
      - city
    Job:
      type: object
      properties:
        jobName:
          type: string
        jobNumber:
          type: string
      required:
      - jobName
      - jobNumber
    Shipping:
      type: object
      properties:
        shippingBranch:
          type: number
        address:
          $ref: '#/components/schemas/Address'
        shippingMethod:
          type: string
      required:
      - shippingBranch
      - address
      - shippingMethod
