openapi: 3.2.0
info:
  title: Beacon Rest Services Get Current User Permission API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: GetCurrentUserPermission
paths:
  /getCurrentUserPermission:
    get:
      operationId: V2Controller_getCurrentUserPermission
      summary: Returns current user permissions
      description: Returns current user permissions as well as the original permissions defaulted to the user.
      parameters: []
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCurrentUserPermissionResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - GetCurrentUserPermission
components:
  schemas:
    Price:
      type: object
      properties:
        'Yes':
          type: boolean
        'No':
          type: boolean
      required:
      - 'Yes'
      - 'No'
    Shipping:
      type: object
      properties:
        shippingBranch:
          type: number
        address:
          $ref: '#/components/schemas/Address'
        shippingMethod:
          type: string
      required:
      - shippingBranch
      - address
      - shippingMethod
    Quote:
      type: object
      properties:
        edit:
          type: boolean
        upload:
          type: boolean
        submit:
          type: boolean
        update:
          type: boolean
        submitForm:
          type: boolean
        queryList:
          type: boolean
        queryListOpen:
          type: boolean
        queryListInProgress:
          type: boolean
        queryListProcessed:
          type: boolean
        queryDetailOpen:
          type: boolean
        queryDetailInProgress:
          type: boolean
        queryDetailProcessed:
          type: boolean
      required:
      - edit
      - upload
      - submit
      - update
      - submitForm
      - queryList
      - queryListOpen
      - queryListInProgress
      - queryListProcessed
      - queryDetailOpen
      - queryDetailInProgress
      - queryDetailProcessed
    Address:
      type: object
      properties:
        postalCode:
          type: string
        state:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        country:
          type: string
        city:
          type: string
      required:
      - postalCode
      - state
      - address1
      - address2
      - address3
      - country
      - city
    Quotes:
      type: object
      properties:
        View:
          type: boolean
        Manage:
          type: boolean
        'No':
          type: boolean
      required:
      - View
      - Manage
      - 'No'
    OrderHistory:
      type: object
      properties:
        YesWithoutPricing:
          type: boolean
        YesWithPricing:
          type: boolean
        'No':
          type: boolean
      required:
      - YesWithoutPricing
      - YesWithPricing
      - 'No'
    Computed:
      type: object
      properties:
        price:
          type: boolean
        order:
          $ref: '#/components/schemas/Order'
        orderhistory:
          $ref: '#/components/schemas/Orderhistory'
        quote:
          $ref: '#/components/schemas/Quote'
        rebate:
          $ref: '#/components/schemas/Rebate'
      required:
      - price
      - order
      - orderhistory
      - quote
      - rebate
    getCurrentUserPermissionResponse:
      type: object
      properties:
        original:
          $ref: '#/components/schemas/Original'
        computed:
          $ref: '#/components/schemas/Computed'
      required:
      - original
      - computed
    Original:
      type: object
      properties:
        Price:
          $ref: '#/components/schemas/Price'
        PlaceOrder:
          $ref: '#/components/schemas/Price'
        OrderHistory:
          $ref: '#/components/schemas/OrderHistory'
        Quotes:
          $ref: '#/components/schemas/Quotes'
        RebateView:
          $ref: '#/components/schemas/Price'
      required:
      - Price
      - PlaceOrder
      - OrderHistory
      - Quotes
      - RebateView
    Order:
      type: object
      properties:
        total:
          type: number
        sellingBranch:
          type: string
        accountId:
          type: string
        orderNumber:
          type: string
        job:
          $ref: '#/components/schemas/Job'
        purchaseOrderNo:
          type: string
        creditHold:
          type: string
        shipping:
          $ref: '#/components/schemas/Shipping'
        orderPlacedDate:
          type: string
        tax:
          type: number
        orderStatusCode:
          type: string
        subTotal:
          type: number
        orderId:
          type: string
        specialInstruction:
          type: string
        UUID:
          type: string
      required:
      - total
      - sellingBranch
      - accountId
      - orderNumber
      - job
      - purchaseOrderNo
      - creditHold
      - shipping
      - orderPlacedDate
      - tax
      - orderStatusCode
      - subTotal
      - orderId
      - specialInstruction
      - UUID
    Orderhistory:
      type: object
      properties:
        queryList:
          type: boolean
        queryDetail:
          type: boolean
        withPrice:
          type: boolean
        withoutPrice:
          type: boolean
      required:
      - queryList
      - queryDetail
      - withPrice
      - withoutPrice
    Job:
      type: object
      properties:
        jobName:
          type: string
        jobNumber:
          type: string
      required:
      - jobName
      - jobNumber
    Rebate:
      type: object
      properties:
        submit:
          type: boolean
        landing:
          type: boolean
        form:
          type: boolean
        thankyou:
          type: boolean
        denied:
          type: boolean
        redeemedSummary:
          type: boolean
        redeemedDetail:
          type: boolean
      required:
      - submit
      - landing
      - form
      - thankyou
      - denied
      - redeemedSummary
      - redeemedDetail
