openapi: 3.2.0
info:
  title: Beacon Rest Services Cart Items API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Cart Items
paths:
  /cartItems:
    get:
      operationId: V2Controller_cartItems
      summary: Retrieves items from cart
      description: Retrieves added items from the cart for the user profile within selected account. This end point allows you to return variations of each item.
      parameters:
      - name: showItemVariations
        required: false
        in: path
        description: Default is false. If "true", display variations of each item.
        schema:
          type: string
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cartItemsResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - Cart Items
components:
  schemas:
    LastSelectedJob:
      type: object
      properties:
        jobName:
          type: string
        jobNumber:
          type: string
      required:
      - jobName
      - jobNumber
    cartItemsResponse:
      type: object
      properties:
        atgOrderId:
          type: string
        lastSelectedJob:
          $ref: '#/components/schemas/LastSelectedJob'
        cartLineItems:
          type: number
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        lastSelectedAccount:
          $ref: '#/components/schemas/LastSelectedAccount'
      required:
      - atgOrderId
      - lastSelectedJob
      - cartLineItems
      - items
      - lastSelectedAccount
    Item:
      type: object
      properties:
        filter:
          type: string
      required:
      - filter
    LastSelectedAccount:
      type: object
      properties:
        accountName:
          type: string
        accountEnabled:
          type: boolean
        accountLegacyId:
          type: string
        accountViewPrices:
          type: boolean
        addCustomSteel:
          type: boolean
        cashAccount:
          type: boolean
        isAccountClosed:
          type: boolean
      required:
      - accountName
      - accountEnabled
      - accountLegacyId
      - accountViewPrices
      - addCustomSteel
      - cashAccount
      - isAccountClosed
