openapi: 3.2.0
info:
  title: Beacon Rest Services Get Saved Order Confirmation Info API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: GetSavedOrderConfirmationInfo
paths:
  /getSavedOrderConfirmationInfo:
    post:
      operationId: V2Controller_getSavedOrderConfirmationInfo
      summary: Returns saved or pending order confirmation information
      description: Returns saved or pending order confirmation information for given saved order Id.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getSavedOrderConfirmationInfoBody'
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getSavedOrderConfirmationInfoResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - GetSavedOrderConfirmationInfo
components:
  schemas:
    BranchAddress:
      type: object
      properties:
        displayName:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        country:
          type: string
        city:
          type: string
        state:
          type: string
        stateValue:
          type: string
        postalCode:
          type: string
        phoneNumber:
          type: string
      required:
      - displayName
      - address1
      - address2
      - address3
      - country
      - city
      - state
      - stateValue
      - postalCode
      - phoneNumber
    ContactInfo:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        nickName:
          type: string
        phoneNumber:
          type: string
      required:
      - firstName
      - lastName
      - nickName
      - phoneNumber
    RequiredFields:
      type: object
      properties:
        deliveryOption:
          type: boolean
        deliveryDate:
          type: boolean
        deliveryTime:
          type: boolean
        shippingMethod:
          type: boolean
        shippingAddress:
          type: boolean
        postalCode:
          type: boolean
        state:
          type: boolean
        address1:
          type: boolean
        address2:
          type: boolean
        address3:
          type: boolean
        country:
          type: boolean
        city:
          type: boolean
        branchName:
          type: boolean
        contactInfo:
          type: boolean
        firstName:
          type: boolean
        lastName:
          type: boolean
        nickName:
          type: boolean
        phoneNumber:
          type: boolean
        instructions:
          type: boolean
        po:
          type: boolean
        jobName:
          type: boolean
        jobAccounts:
          type: boolean
      required:
      - deliveryOption
      - deliveryDate
      - deliveryTime
      - shippingMethod
      - shippingAddress
      - postalCode
      - state
      - address1
      - address2
      - address3
      - country
      - city
      - branchName
      - contactInfo
      - firstName
      - lastName
      - nickName
      - phoneNumber
      - instructions
      - po
      - jobName
      - jobAccounts
    AssignApproval:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
      required:
      - id
      - name
      - email
    ShippingMethod:
      type: object
      properties:
        displayName:
          type: string
        value:
          type: string
        selected:
          type: boolean
      required:
      - displayName
      - value
      - selected
    ShippingAddress:
      type: object
      properties:
        addressBookId:
          type: string
        nickName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        city:
          type: string
        stateValue:
          type: string
        states:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        postalCode:
          type: string
        countryValue:
          type: string
        countries:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        phoneNumber:
          type: string
      required:
      - addressBookId
      - nickName
      - firstName
      - lastName
      - address1
      - address2
      - address3
      - city
      - stateValue
      - states
      - postalCode
      - countryValue
      - countries
      - phoneNumber
    DeliveryOption:
      type: object
      properties:
        displayName:
          type: string
        value:
          type: string
        selected:
          type: boolean
      required:
      - displayName
      - value
      - selected
    getSavedOrderConfirmationInfoResponse:
      type: object
      properties:
        id:
          type: string
        mincronId:
          type: string
        displayName:
          type: string
        accountNumber:
          type: string
        accountName:
          type: string
        accountNameOriginal:
          type: string
        creationDate:
          type: string
        createdUser:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        createdUserEmail:
          type: string
        submittedDate:
          type: string
        status:
          type: string
        statusDisplayName:
          type: string
        readOnly:
          type: boolean
        siteId:
          type: string
        organizationId:
          type: string
        contactInfo:
          $ref: '#/components/schemas/ContactInfo'
        lastModifiedDate:
          type: string
        lastModifiedUser:
          type: string
        deleteStatus:
          type: boolean
        job:
          $ref: '#/components/schemas/Job'
        jobAccounts:
          $ref: '#/components/schemas/JobAccounts'
        shippingMethod:
          type: string
        shippingMethodValue:
          type: string
        shippingMethods:
          type: array
          items:
            $ref: '#/components/schemas/ShippingMethod'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
        shippingAddressTitle:
          type: string
        branchName:
          type: string
        branchAddress:
          $ref: '#/components/schemas/BranchAddress'
        instructions:
          type: string
        commerceItems:
          type: array
          items:
            $ref: '#/components/schemas/CommerceItem'
        requiredFields:
          $ref: '#/components/schemas/RequiredFields'
        approvedBy:
          type: string
        po:
          type: string
        emailAddress:
          type: array
          items:
            type: string
        deliveryOption:
          type: string
        deliveryOptionValue:
          type: string
        deliveryOptions:
          type: array
          items:
            $ref: '#/components/schemas/ShippingMethod'
        deliveryDate:
          type: string
        deliveryTime:
          type: string
        deliveryTimes:
          type: array
          items:
            $ref: '#/components/schemas/ShippingMethod'
        itemsTotal:
          type: number
        taxes:
          type: number
        otherCharges:
          type: number
        subTotal:
          type: number
        addressBooks:
          type: array
          items:
            $ref: '#/components/schemas/AddressBook'
        addressBook:
          $ref: '#/components/schemas/AddressBook'
        storeLocatorItemId:
          type: string
        rejectReason:
          type: string
        assignApprovalDisplayText:
          type: string
        assignApproval:
          $ref: '#/components/schemas/AssignApproval'
        rejectUserDisplayText:
          type: string
        rejectUser:
          $ref: '#/components/schemas/AssignApproval'
        showDeliveryNotification:
          type: boolean
        accountBranchState:
          type: string
        displaySubTotalMsg:
          type: boolean
        subTotalMsg:
          type: string
        thankYouMsg:
          type: string
      required:
      - id
      - mincronId
      - displayName
      - accountNumber
      - accountName
      - accountNameOriginal
      - creationDate
      - createdUser
      - firstName
      - lastName
      - createdUserEmail
      - submittedDate
      - status
      - statusDisplayName
      - readOnly
      - siteId
      - organizationId
      - contactInfo
      - lastModifiedDate
      - lastModifiedUser
      - deleteStatus
      - job
      - jobAccounts
      - shippingMethod
      - shippingMethodValue
      - shippingMethods
      - shippingAddress
      - shippingAddressTitle
      - branchName
      - branchAddress
      - instructions
      - commerceItems
      - requiredFields
      - approvedBy
      - po
      - emailAddress
      - deliveryOption
      - deliveryOptionValue
      - deliveryOptions
      - deliveryDate
      - deliveryTime
      - deliveryTimes
      - itemsTotal
      - taxes
      - otherCharges
      - subTotal
      - addressBooks
      - addressBook
      - storeLocatorItemId
      - rejectReason
      - assignApprovalDisplayText
      - assignApproval
      - rejectUserDisplayText
      - rejectUser
      - showDeliveryNotification
      - accountBranchState
      - displaySubTotalMsg
      - subTotalMsg
      - thankYouMsg
    getSavedOrderConfirmationInfoBody:
      type: object
      properties:
        id:
          type: string
      required:
      - id
    JobAccounts:
      type: object
      properties:
        unavailable:
          type: boolean
        unavailableMsg:
          type: string
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/Job'
      required:
      - unavailable
      - unavailableMsg
      - jobs
    AddressBook:
      type: object
      properties:
        addressBookId:
          type: string
        accountLegacyId:
          type: string
        accountName:
          type: string
        addressBookInfo:
          $ref: '#/components/schemas/AddressBookInfo'
      required:
      - addressBookId
      - accountLegacyId
      - accountName
      - addressBookInfo
    CommerceItem:
      type: object
      properties:
        id:
          type: string
        imageUrl:
          type: string
        imageOnErrorUrl:
          type: string
        thumbImageUrl:
          type: string
        pdpUrl:
          type: string
        description:
          type: string
        itemNumber:
          type: string
        price:
          type: number
        quantity:
          type: number
        uom:
          type: string
        subTotal:
          type: number
        deleteStatus:
          type: boolean
        vendorColorId:
          type: string
        productId:
          type: string
        itemGrayOutLevel:
          type: string
      required:
      - id
      - imageUrl
      - imageOnErrorUrl
      - thumbImageUrl
      - pdpUrl
      - description
      - itemNumber
      - price
      - quantity
      - uom
      - subTotal
      - deleteStatus
      - vendorColorId
      - productId
      - itemGrayOutLevel
    Job:
      type: object
      properties:
        jobName:
          type: string
        jobNumber:
          type: string
      required:
      - jobName
      - jobNumber
    AddressBookInfo:
      type: object
      properties:
        nickName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        stateValue:
          type: string
        postalCode:
          type: string
        country:
          type: string
        countryValue:
          type: string
        phoneNumber:
          type: string
      required:
      - nickName
      - firstName
      - lastName
      - address1
      - address2
      - city
      - state
      - stateValue
      - postalCode
      - country
      - countryValue
      - phoneNumber
