openapi: 3.2.0
info:
  title: Beacon Rest Services Item Details API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: ItemDetails
paths:
  /itemDetails:
    get:
      operationId: V3Controller_itemDetails
      summary: Get items details
      description: This service returns product details based on Product or item Id.
      parameters:
      - name: productId
        required: true
        in: query
        description: Product Id
        schema:
          type: string
      - name: itemNumber
        required: false
        in: query
        description: Item number(SKU ID)
        schema:
          type: string
      - name: accountId
        required: false
        in: query
        description: Account Id
        schema:
          type: string
      - name: jobNumber
        required: false
        in: query
        description: Job Number
        schema:
          type: string
      - name: uom
        required: false
        in: query
        description: Unit of Measure
        schema:
          type: string
      - name: showHoverAttrs
        required: false
        in: query
        description: if "true", display hover attributes
        schema:
          type: string
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/itemDetailsResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      security:
      - basic: []
      tags:
      - ItemDetails
components:
  schemas:
    Specification:
      type: object
      properties:
        Shingles_Per_Square:
          type: string
        Algae_Resistance:
          type: string
        Coverage_Per_Square:
          type: string
        Bundles_Per_Square:
          type: string
        Nominal_Size:
          type: string
        Net_Free_Vent_Area__NFVA_:
          type: string
        Exposure:
          type: string
        Wind_Resistance:
          type: string
      required:
      - Shingles_Per_Square
      - Algae_Resistance
      - Coverage_Per_Square
      - Bundles_Per_Square
      - Nominal_Size
      - Net_Free_Vent_Area__NFVA_
      - Exposure
      - Wind_Resistance
    Product:
      type: object
      properties:
        productImage:
          type: string
        productOnErrorImage:
          type: string
        longDesc:
          type: string
        manufactureNumber:
          type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        shortDesc:
          type: string
        itemNumber:
          type: string
        hoverAttributes:
          $ref: '#/components/schemas/HoverAttributes'
        productName:
          type: string
        productId:
          type: string
        baseProductName:
          type: string
        internalProductName:
          type: string
        brand:
          type: string
        url:
          type: string
        relatedProducts:
          type: array
          items:
            type: string
      required:
      - productImage
      - productOnErrorImage
      - longDesc
      - manufactureNumber
      - categories
      - shortDesc
      - itemNumber
      - hoverAttributes
      - productName
      - productId
      - baseProductName
      - internalProductName
      - brand
      - url
      - relatedProducts
    Thickness:
      type: object
      properties:
        2mm:
          type: array
          items:
            type: string
        4mm:
          type: array
          items:
            type: string
        6mm:
          type: array
          items:
            type: string
      required:
      - 2mm
      - 4mm
      - 6mm
    Variations2:
      type: object
      properties:
        color:
          $ref: '#/components/schemas/Color'
        size:
          $ref: '#/components/schemas/Size'
        thickness:
          $ref: '#/components/schemas/Thickness'
      required:
      - color
      - size
      - thickness
    Size:
      type: object
      properties:
        12x10:
          type: array
          items:
            type: string
        4x4:
          type: array
          items:
            type: string
      required:
      - 12x10
      - 4x4
    itemDetailsResponse:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/Product'
        message:
          type: string
        specification:
          $ref: '#/components/schemas/Specification'
        resource:
          $ref: '#/components/schemas/Resource'
        currentSKU:
          $ref: '#/components/schemas/CurrentSKU'
        skuList:
          type: array
          items:
            $ref: '#/components/schemas/SkuList'
        variations:
          $ref: '#/components/schemas/Variations2'
      required:
      - product
      - message
      - specification
      - resource
      - currentSKU
      - skuList
      - variations
    CurrentSKU:
      type: object
      properties:
        currentUOM:
          type: string
        color:
          type: string
        manufactureNumber:
          type: string
        unitPrice:
          type: number
        itemNumber:
          type: string
        productNumber:
          type: string
        uomlist:
          type: array
          items:
            type: string
        itemImage:
          type: string
        heroImage:
          type: string
        thumbImage:
          type: string
        swatchImage:
          type: string
        skuShortDesc:
          type: string
        auxiliaryImages:
          type: array
          items:
            type: string
      required:
      - currentUOM
      - color
      - manufactureNumber
      - unitPrice
      - itemNumber
      - productNumber
      - uomlist
      - itemImage
      - heroImage
      - thumbImage
      - swatchImage
      - skuShortDesc
      - auxiliaryImages
    Color:
      type: object
      properties:
        White:
          type: array
          items:
            type: string
        Dover:
          type: array
          items:
            type: string
      required:
      - White
      - Dover
    SkuList:
      type: object
      properties:
        currentUOM:
          type: string
        color:
          type: string
        unitPrice:
          type: number
        itemNumber:
          type: string
        productNumber:
          type: string
        itemImage:
          type: string
        heroImage:
          type: string
        thumbImage:
          type: string
        swatchImage:
          type: string
        skuShortDesc:
          type: string
        auxiliaryImages:
          type: array
          items:
            type: string
      required:
      - currentUOM
      - color
      - unitPrice
      - itemNumber
      - productNumber
      - itemImage
      - heroImage
      - thumbImage
      - swatchImage
      - skuShortDesc
      - auxiliaryImages
    Resource:
      type: object
      properties:
        General Instructrions:
          type: string
        Warranty:
          type: string
        MSDS:
          type: string
        Brochure:
          type: string
      required:
      - General Instructrions
      - Warranty
      - MSDS
      - Brochure
    Category:
      type: object
      properties:
        categoryName:
          type: string
        categoryId:
          type: string
      required:
      - categoryName
      - categoryId
    HoverAttributes:
      type: object
      properties:
        sellingUom:
          type: string
        piecesPerUom:
          type: string
        coverageUom:
          type: string
        ppCoverageUom:
          type: string
        lengthExposure:
          type: string
        widthExposure:
          type: string
        lengthHover:
          type: string
        widthHover:
          type: string
        ncpSellingUom:
          type: string
        gcpSellingUom:
          type: string
        sslvoDimensionIn:
          type: string
        sswhoDimensionOption1In:
          type: string
        sswhoDimensionOption2In:
          type: string
        sswhoDimensionOption3In:
          type: string
        lslvoDimensionIn:
          type: string
        lswhoDimensionIn:
          type: string
        rvlvoDimensionIn:
          type: string
        rvwhoDimensionIn:
          type: string
        nfvaHover:
          type: string
        nfvaUomHover:
          type: string
        fhLapIn:
          type: string
        fvLapIn:
          type: string
        chLapIn:
          type: string
        cvLapIn:
          type: string
        cfmValue:
          type: string
        cfmUom:
          type: string
      required:
      - sellingUom
      - piecesPerUom
      - coverageUom
      - ppCoverageUom
      - lengthExposure
      - widthExposure
      - lengthHover
      - widthHover
      - ncpSellingUom
      - gcpSellingUom
      - sslvoDimensionIn
      - sswhoDimensionOption1In
      - sswhoDimensionOption2In
      - sswhoDimensionOption3In
      - lslvoDimensionIn
      - lswhoDimensionIn
      - rvlvoDimensionIn
      - rvwhoDimensionIn
      - nfvaHover
      - nfvaUomHover
      - fhLapIn
      - fvLapIn
      - chLapIn
      - cvLapIn
      - cfmValue
      - cfmUom
