openapi: 3.2.0
info:
  title: Beacon Rest Services Exchange Okta Eagle View Authorization…
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: ExchangeOktaEagleViewAuthorizationCode
paths:
  /exchangeOktaEagleViewAuthorizationCode:
    get:
      operationId: V2Controller_exchangeOktaEagleViewAuthorizationCode
      summary: Returns access token by authorization code
      description: Returns authorization code and sends to Eagleview to acquire access token for three-legged authorization flow.
      parameters: []
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exchangeOktaEagleViewAuthorizationCodeResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - ExchangeOktaEagleViewAuthorizationCode
components:
  schemas:
    exchangeOktaEagleViewAuthorizationCodeResponse:
      type: object
      properties:
        code:
          type: string
        state:
          type: string
      required:
      - code
      - state
