openapi: 3.2.0
info:
  title: Beacon Rest Services Beacon Stack (BASE URL…
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Beacon Stack (BASE URL:- https://beacon-api-x7xzzdp35a-uk.a.run.app)
paths:
  /api/address-validation/getaddress:
    post:
      operationId: AddressValidationController_getAddress
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Beacon Stack (BASE URL:- https://beacon-api-x7xzzdp35a-uk.a.run.app)
      summary: Address validation controller get address
      x-summary-source: derived
  /api/address-validation/getstreetwildsearch:
    post:
      operationId: AddressValidationController_getStreetWildSearch
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Beacon Stack (BASE URL:- https://beacon-api-x7xzzdp35a-uk.a.run.app)
      summary: Address validation controller get street wild search
      x-summary-source: derived
