openapi: 3.2.0
info:
  title: Beacon Rest Services Get User Register Token API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: GetUserRegisterToken
paths:
  /getUserRegisterToken:
    get:
      operationId: V2Controller_getUserRegisterToken
      summary: Returns token for registered user
      description: Users with an active Beacon account number can sign up to use PRO+. When the active user signs up, a token is generated which allows user to continue the session in PRO+.
      parameters: []
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUserRegisterTokenResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - GetUserRegisterToken
components:
  schemas:
    UserRegInfo:
      type: object
      properties:
        userRegisterToken:
          type: string
      required:
      - userRegisterToken
    getUserRegisterTokenResponse:
      type: object
      properties:
        userRegInfo:
          $ref: '#/components/schemas/UserRegInfo'
      required:
      - userRegInfo
