openapi: 3.2.0
info:
  title: Beacon Rest Services Validate User By Account API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: ValidateUserByAccount
paths:
  /validateUserByAccount:
    post:
      operationId: V2Controller_validateUserByAccount
      summary: Validates user by account information
      description: Validates that user’s account name, account number and zip code after user signs up for PRO+ to ensure it matches what is stored in database.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/validateUserByAccountBody'
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validateUserByAccountResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - ValidateUserByAccount
components:
  schemas:
    UserRegInfo:
      type: object
      properties:
        userRegisterToken:
          type: string
      required:
      - userRegisterToken
    BranchSelection:
      type: object
      properties:
        accountId:
          type: string
        accountName:
          type: string
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
      required:
      - accountId
      - accountName
      - branches
    validateUserByAccountResponse:
      type: object
      properties:
        userRegInfo:
          $ref: '#/components/schemas/UserRegInfo'
        showBranchSelection:
          type: boolean
        branchSelection:
          $ref: '#/components/schemas/BranchSelection'
        retryTimesLeft:
          type: number
        needLogin:
          type: boolean
        needRetry:
          type: boolean
        needContactSupport:
          type: boolean
        needGetUserRegisterToken:
          type: boolean
        needInvoice:
          type: boolean
        registerSuccess:
          type: boolean
      required:
      - userRegInfo
      - showBranchSelection
      - branchSelection
      - retryTimesLeft
      - needLogin
      - needRetry
      - needContactSupport
      - needGetUserRegisterToken
      - needInvoice
      - registerSuccess
    Address:
      type: object
      properties:
        postalCode:
          type: string
        state:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        country:
          type: string
        city:
          type: string
      required:
      - postalCode
      - state
      - address1
      - address2
      - address3
      - country
      - city
    Branch:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
        branchNumber:
          type: string
        branchName:
          type: string
        branchPhone:
          type: string
        branchRegionId:
          type: string
        company:
          type: string
        companyName:
          type: string
        division:
          type: string
        divisionName:
          type: string
        market:
          type: string
      required:
      - address
      - branchNumber
      - branchName
      - branchPhone
      - branchRegionId
      - company
      - companyName
      - division
      - divisionName
      - market
    validateUserByAccountBody:
      type: object
      properties:
        emailAddress:
          type: string
        companyName:
          type: string
        account:
          type: string
        invoice:
          type: string
        invoiceDate:
          type: string
      required:
      - emailAddress
      - companyName
      - account
      - invoice
      - invoiceDate
