openapi: 3.2.0
info:
  title: Beacon Rest Services Update Template API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: UpdateTemplate
paths:
  /updateTemplate:
    post:
      operationId: V2Controller_updateTemplate
      summary: Updates template
      description: 'Updates template name or items in a template.


        Request body: required


        templateId: required


        account: required


        templateName: optional


        action: optional


        items: optional


        action is "createItem"


        itemNumber: required


        unitOfMeasure: Optional if invokeBy is "store"; otherwise, this value is required


        quantity: required


        matchColor: optional.format: "vendor color name(code)", example: "Gunmetal Grey(010)" or just "vendor color name", example: "Gunmetal Grey"


        matchMFG: optional


        action is "updateItem"


        templateItemId: required


        itemNumber: required


        unitOfMeasure: Optional if invokeBy is "store"; otherwise, this value is required


        quantity: required


        matchColor: optional, format: "vendor color name(code)", Example: "Gunmetal Grey(010)" or just "vendor color namExample:Example: "Gunmetal Grey"


        matchMFG: optional


        action is "deleteItem"


        templateItemId: required'
      parameters:
      - name: invokeBy
        required: false
        in: path
        description: If value is "store", will do the store logic
        schema:
          type: string
      - name: ignoreInvalidItems
        required: false
        in: path
        description: If "true", will ignore invalid items and continue add valid items to cart, otherwise will return invalid items
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateTemplateBody'
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateTemplateResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - UpdateTemplate
components:
  schemas:
    Item:
      type: object
      properties:
        filter:
          type: string
      required:
      - filter
    updateTemplateResponse:
      type: object
      properties:
        templateId:
          type: string
        templateName:
          type: string
        lastModifiedDate:
          type: string
        accountLegacyId:
          type: string
        accountName:
          type: string
        allItemsUnavailable:
          type: boolean
        itemTotal:
          type: number
        itemSuccessTotal:
          type: number
        detailUrl:
          type: string
      required:
      - templateId
      - templateName
      - lastModifiedDate
      - accountLegacyId
      - accountName
      - allItemsUnavailable
      - itemTotal
      - itemSuccessTotal
      - detailUrl
    updateTemplateBody:
      type: object
      properties:
        templateId:
          type: string
        account:
          type: string
        templateName:
          type: string
        action:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
      required:
      - templateId
      - account
      - templateName
      - action
      - items
