openapi: 3.2.0
info:
  title: Beacon Rest Services Delete Template API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: DeleteTemplate
paths:
  /deleteTemplate:
    post:
      operationId: V2Controller_deleteTemplate
      summary: Deletes template
      description: 'Deletes template(s) for current user by template Id.


        Parameters:


        templateId: The template Id list, separated by comma.Example: "gl35140002,gl35140003,gl35140004"


        account: The account Id


        invokeBy: If value is "store", will do the store logic'
      parameters:
      - name: templateId
        required: true
        in: path
        description: 'The template Id list, separated by comma, Example: "gl35140002,gl35140003,gl35140004"'
        schema:
          type: string
      - name: account
        required: true
        in: path
        description: The account Id
        schema:
          type: string
      - name: invokeBy
        required: false
        in: path
        description: If value is "store", will do the store logic
        schema:
          type: string
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - DeleteTemplate
