openapi: 3.2.0
info:
  title: Beacon Rest Services Get DT Order Detail API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: GetDTOrderDetail
paths:
  /getDTOrderDetail:
    get:
      operationId: V2Controller_getDTOrderDetail
      summary: Returns delivery tracking order information by order Id
      description: Returns delivery tracking status and photos for a specific order Id number.
      parameters:
      - name: orderId
        required: false
        in: path
        description: Order Id
        schema:
          type: string
      - name: showDT
        required: false
        in: path
        description: Flag to show/hide DT order status info, default is true.
        schema:
          type: string
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getDTOrderDetailResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - GetDTOrderDetail
components:
  schemas:
    DTPhoto:
      type: object
      properties:
        ThumbnailUrl:
          type: string
        LargeUrl:
          type: string
        Timestamp:
          type: string
      required:
      - ThumbnailUrl
      - LargeUrl
      - Timestamp
    Info:
      type: object
      properties:
        defaultValue:
          type: string
        imageUrl:
          type: string
        active:
          type: boolean
        key:
          type: string
        value:
          type: string
      required:
      - defaultValue
      - imageUrl
      - active
      - key
      - value
    getDTOrderDetailResponse:
      type: object
      properties:
        DTStatus:
          $ref: '#/components/schemas/DTStatus'
        DTPhotos:
          type: array
          items:
            $ref: '#/components/schemas/DTPhoto'
        branchDTEnabled:
          type: boolean
        DTEnabled:
          type: boolean
        hasDTError:
          type: boolean
      required:
      - DTStatus
      - DTPhotos
      - branchDTEnabled
      - DTEnabled
      - hasDTError
    DTStatus:
      type: object
      properties:
        displayName:
          type: string
        contKey:
          type: string
        contValue:
          type: string
        statusEndDate:
          type: string
        infos:
          type: array
          items:
            $ref: '#/components/schemas/Info'
      required:
      - displayName
      - contKey
      - contValue
      - statusEndDate
      - infos
