openapi: 3.2.0
info:
  title: Beacon Rest Services Categories API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Categories
paths:
  /categories:
    get:
      operationId: V2Controller_categories
      summary: Returns all categories and placement in hierarchy
      description: Returns categories and placement in hierarchy such as residential roofing level 1 and asphalt shingles level 2.
      parameters:
      - name: account
        required: true
        in: path
        description: Account Id
        schema:
          type: string
      - name: showSubCategories
        required: false
        in: path
        description: Default is false and will return categories in level 1. If true, will return level 1 categories and level 2 subcategories.
        schema:
          type: boolean
      - name: categoryNameOrId
        required: false
        in: path
        description: Category name or Id filter.
        schema:
          type: string
      - name: showRecordCount
        required: false
        in: path
        description: Default is false. If true, will return the record count of each category.
        schema:
          type: string
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categoriesResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - Categories
components:
  schemas:
    categoriesResponse:
      type: object
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
      required:
      - categories
    Category:
      type: object
      properties:
        categoryName:
          type: string
        categoryId:
          type: string
      required:
      - categoryName
      - categoryId
