openapi: 3.2.0
info:
  title: Beacon Rest Services Orderhistory V2 API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Orderhistory V2
paths:
  /orderhistory_v2:
    get:
      operationId: V2Controller_orderhistory_v2
      summary: Returns orders listed by order id
      description: Returns order information for each order including order totals, selling branch, special instructions, and shipping information. Default page size is 25 and default page is 1 to accommodate Hover.
      parameters:
      - name: accountId
        required: true
        in: path
        description: Account Id
        schema:
          type: number
      - name: pageSize
        required: false
        in: path
        description: Default page size is 25
        schema:
          type: number
      - name: pageNo
        required: false
        in: path
        description: Default page no is 1
        schema:
          type: number
      - name: searchBy
        required: false
        in: path
        description: <b>searchBy enumeration</b><ul><li>JobName</li><li>ProductOrSKU</li><li>OrderPlacedDate</li><li>MincronOrderNumber</li><li>OrderStatus</li><li>CustPO</li><li>IsPROPlusOrder</li><li>Street</li><li>UUID</li></ul>
        schema:
          type: string
      - name: searchTerm
        required: false
        in: path
        description: <b>When "searchBy" is one of the following enumeration, the "searchTerm" should be populated</b><ul><li>JobName</li><li>ProductOrSKU</li><li>MincronOrderNumber</li><li>CustPO</li><li>Street</li><li>UUID</li></ul>
        schema:
          type: string
      - name: searchStartDate
        required: false
        in: path
        description: '<b>When "searchBy" is "OrderPlacedDate", the "searchStartDate" should be populated, format should be "MM-DD-YYYY", Example: "01-05-2021"</b>'
        schema:
          type: string
      - name: searchEndDate
        required: false
        in: path
        description: '<b>When "searchBy" is "OrderPlacedDate", the "searchEndDate" should be populated, format should be "MM-DD-YYYY", Example: "01-05-2021"</b>'
        schema:
          type: string
      - name: searchEnum
        required: false
        in: path
        description: <b>When "searchBy" is "OrderStatus", the "searchEnum" should be one of the following enumeration:</b><ul><li>Delivered</li><li>Invoiced</li><li>Pending</li><li>Processing</li><li>ReadyDeliveryOrPickUp</li></ul><b>When "searchBy" is "IsPROPlusOrder", the "searchEnum" should be one of the following enumeration:</b><ul><li>No</li><li>Yes</li></ul>
        schema:
          type: string
      - name: orderBy
        required: false
        in: path
        description: <h4>orderBy enumeration</h4><ul><li>MincronOrderNumber ASC/ DESC</li><li>Details ASC / DESC</li><li>IsPROPlusOrder ASC / DESC</li><li>TotalOrderAmount ASC / DESC</li><li>OrderStatus ASC / DESC</li></ul>
        schema:
          type: string
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orderHistoryv2Response'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - Orderhistory V2
components:
  schemas:
    Order:
      type: object
      properties:
        total:
          type: number
        sellingBranch:
          type: string
        accountId:
          type: string
        orderNumber:
          type: string
        job:
          $ref: '#/components/schemas/Job'
        purchaseOrderNo:
          type: string
        creditHold:
          type: string
        shipping:
          $ref: '#/components/schemas/Shipping'
        orderPlacedDate:
          type: string
        tax:
          type: number
        orderStatusCode:
          type: string
        subTotal:
          type: number
        orderId:
          type: string
        specialInstruction:
          type: string
        UUID:
          type: string
      required:
      - total
      - sellingBranch
      - accountId
      - orderNumber
      - job
      - purchaseOrderNo
      - creditHold
      - shipping
      - orderPlacedDate
      - tax
      - orderStatusCode
      - subTotal
      - orderId
      - specialInstruction
      - UUID
    Address:
      type: object
      properties:
        postalCode:
          type: string
        state:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        country:
          type: string
        city:
          type: string
      required:
      - postalCode
      - state
      - address1
      - address2
      - address3
      - country
      - city
    Job:
      type: object
      properties:
        jobName:
          type: string
        jobNumber:
          type: string
      required:
      - jobName
      - jobNumber
    orderHistoryv2Response:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
      - orders
      - pagination
    Next:
      type: object
      properties:
        available:
          type: boolean
        label:
          type: string
        page:
          type: number
      required:
      - available
      - label
      - page
    Result:
      type: object
      properties:
        pageRows:
          type: number
        pages:
          type: number
        page:
          type: number
        rows:
          type: number
        rowsPerPage:
          type: number
      required:
      - pageRows
      - pages
      - page
      - rows
      - rowsPerPage
    Pagination:
      type: object
      properties:
        next:
          $ref: '#/components/schemas/Next'
        previous:
          $ref: '#/components/schemas/Next'
        pageSize:
          type: number
        currentPage:
          type: number
        totalCount:
          type: number
        results:
          type: array
          items:
            $ref: '#/components/schemas/Result'
      required:
      - next
      - previous
      - pageSize
      - currentPage
      - totalCount
      - results
    Shipping:
      type: object
      properties:
        shippingBranch:
          type: number
        address:
          $ref: '#/components/schemas/Address'
        shippingMethod:
          type: string
      required:
      - shippingBranch
      - address
      - shippingMethod
