openapi: 3.2.0
info:
  title: Beacon Rest Services Update Saved Order Shipping Info API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: UpdateSavedOrderShippingInfo
paths:
  /updateSavedOrderShippingInfo:
    post:
      operationId: V2Controller_updateSavedOrderShippingInfo
      summary: Returns saved or pending order shipping information
      description: Updates saved or pending order shipping information for a given saved order Id.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateSavedOrderShippingInfoBody'
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - UpdateSavedOrderShippingInfo
components:
  schemas:
    ShippingAddress:
      type: object
      properties:
        addressBookId:
          type: string
        nickName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        city:
          type: string
        stateValue:
          type: string
        states:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        postalCode:
          type: string
        countryValue:
          type: string
        countries:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        phoneNumber:
          type: string
      required:
      - addressBookId
      - nickName
      - firstName
      - lastName
      - address1
      - address2
      - address3
      - city
      - stateValue
      - states
      - postalCode
      - countryValue
      - countries
      - phoneNumber
    updateSavedOrderShippingInfoBody:
      type: object
      properties:
        orderId:
          type: string
        deliveryOption:
          type: string
        deliveryDate:
          type: string
        deliveryTime:
          type: string
        shippingMethod:
          type: string
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
        branchName:
          type: string
        contactInfo:
          $ref: '#/components/schemas/ContactInfo'
        instructions:
          type: string
      required:
      - orderId
      - deliveryOption
      - deliveryDate
      - deliveryTime
      - shippingMethod
      - shippingAddress
      - branchName
      - contactInfo
      - instructions
    ContactInfo:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        nickName:
          type: string
        phoneNumber:
          type: string
      required:
      - firstName
      - lastName
      - nickName
      - phoneNumber
    DeliveryOption:
      type: object
      properties:
        displayName:
          type: string
        value:
          type: string
        selected:
          type: boolean
      required:
      - displayName
      - value
      - selected
