openapi: 3.2.0
info:
  title: Beacon Rest Services Get Order Shipping Info API
  description: 'A combination of all methods in the beacon-api


    [ BASE URL: https://beaconproplus.com


    Beacon ProPlus


    Version 1: https://beaconproplus.com/v1/rest/com/becn


    Version 2: https://beaconproplus.com/v2/rest/com/becn


    Version 3: https://beaconproplus.com/v3/rest/com/becn


    Beacon Stack


    [ BASE URL: https://beacon-api-x7xzzdp35a-uk.a.run.app


    Version 1: https://beacon-api-x7xzzdp35a-uk.a.run.app/v1/rest/com/becn/


    Version 2: https://beacon-api-x7xzzdp35a-uk.a.run.app/v2/rest/com/becn/


    Version 3…'
  version: '1.0'
  contact: {}
servers: []
tags:
- name: GetOrderShippingInfo
paths:
  /getOrderShippingInfo:
    get:
      operationId: V2Controller_getOrderShippingInfo
      summary: Returns current order shipping information
      description: Returns current order shipping information.
      parameters: []
      responses:
        '200':
          description: successful operation<br><br>refer to the <i>API Uniform Format</i> dropdown above
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getOrderShippingInfoResponse'
        '400':
          description: Bad Request, accountId is invalid.
        '401':
          description: Unauthorized, the authorization bearer token is invalid.
        '405':
          description: Method not allowed, the request method is not valid for this API or this API is not available.
        '500':
          description: Internal exception.
      tags:
      - GetOrderShippingInfo
components:
  schemas:
    BranchAddress:
      type: object
      properties:
        displayName:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        country:
          type: string
        city:
          type: string
        state:
          type: string
        stateValue:
          type: string
        postalCode:
          type: string
        phoneNumber:
          type: string
      required:
      - displayName
      - address1
      - address2
      - address3
      - country
      - city
      - state
      - stateValue
      - postalCode
      - phoneNumber
    ContactInfo:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        nickName:
          type: string
        phoneNumber:
          type: string
      required:
      - firstName
      - lastName
      - nickName
      - phoneNumber
    ShippingAddress:
      type: object
      properties:
        addressBookId:
          type: string
        nickName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        city:
          type: string
        stateValue:
          type: string
        states:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        postalCode:
          type: string
        countryValue:
          type: string
        countries:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        phoneNumber:
          type: string
      required:
      - addressBookId
      - nickName
      - firstName
      - lastName
      - address1
      - address2
      - address3
      - city
      - stateValue
      - states
      - postalCode
      - countryValue
      - countries
      - phoneNumber
    DeliveryOption:
      type: object
      properties:
        displayName:
          type: string
        value:
          type: string
        selected:
          type: boolean
      required:
      - displayName
      - value
      - selected
    ShippingAddress2:
      type: object
      properties:
        address1:
          type: string
        address2:
          type: string
        address3:
          type: string
        country:
          type: string
        city:
          type: string
        state:
          type: string
        states:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        postalCode:
          type: string
      required:
      - address1
      - address2
      - address3
      - country
      - city
      - state
      - states
      - postalCode
    AddressBook:
      type: object
      properties:
        addressBookId:
          type: string
        accountLegacyId:
          type: string
        accountName:
          type: string
        addressBookInfo:
          $ref: '#/components/schemas/AddressBookInfo'
      required:
      - addressBookId
      - accountLegacyId
      - accountName
      - addressBookInfo
    getOrderShippingInfoResponse:
      type: object
      properties:
        deliveryOption:
          type: string
        deliveryOptionValue:
          type: string
        deliveryOptions:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        deliveryDate:
          type: string
        deliveryTime:
          type: string
        deliveryTimes:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        expressDeliveryTimes:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        shippingMethod:
          type: string
        shippingMethodValue:
          type: string
        shippingMethods:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
        addressBooks:
          type: array
          items:
            $ref: '#/components/schemas/AddressBook'
        addressBook:
          $ref: '#/components/schemas/AddressBook2'
        branchAddress:
          $ref: '#/components/schemas/BranchAddress'
        instructions:
          type: string
      required:
      - deliveryOption
      - deliveryOptionValue
      - deliveryOptions
      - deliveryDate
      - deliveryTime
      - deliveryTimes
      - expressDeliveryTimes
      - shippingMethod
      - shippingMethodValue
      - shippingMethods
      - shippingAddress
      - addressBooks
      - addressBook
      - branchAddress
      - instructions
    AddressBookInfo:
      type: object
      properties:
        nickName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        stateValue:
          type: string
        postalCode:
          type: string
        country:
          type: string
        countryValue:
          type: string
        phoneNumber:
          type: string
      required:
      - nickName
      - firstName
      - lastName
      - address1
      - address2
      - city
      - state
      - stateValue
      - postalCode
      - country
      - countryValue
      - phoneNumber
    AddressBook2:
      type: object
      properties:
        id:
          type: string
        displayName:
          type: string
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress2'
        contactInfo:
          $ref: '#/components/schemas/ContactInfo'
      required:
      - id
      - displayName
      - shippingAddress
      - contactInfo
